name: "New Paper Server"
minecraft:
  loader: "paper"
  version: "1.21.1"

world:
  mode: "generated"
  seed: ""
  name: "world"

plugins: []

configs:
  files:
    - template: "server.properties.hbs"
      output: "server.properties"
      data:
        motd: "New MC Server"
        maxPlayers: 10
        enforceSecureProfile: false

overrides:
  - path: "server.properties:view-distance"
    value: 10

mergePolicy:
  arrays: "replace"

