import { useEffect, useMemo, useState } from 'react'
import {
  createProject,
  fetchProjects,
  importProjectRepo,
  triggerManifest,
  triggerBuild,
  fetchBuilds,
  fetchBuild,
  scanProjectAssets,
  type ProjectSummary,
  type BuildJob,
} from '../lib/api'
import { subscribeProjectsUpdated } from '../lib/events'

function TestTools() {
  const [projects, setProjects] = useState<ProjectSummary[]>([])
  const [busy, setBusy] = useState(false)
  const [logs, setLogs] = useState<string[]>([])
  const [error, setError] = useState<string | null>(null)
  const [builds, setBuilds] = useState<BuildJob[]>([])

  const sortedProjects = useMemo(
    () => [...projects].sort((a, b) => (a.updatedAt < b.updatedAt ? 1 : -1)),
    [projects],
  )

  useEffect(() => {
    let active = true

    const load = () => {
      fetchProjects()
        .then((items) => {
          if (!active) return
          setProjects(items)
          setError(null)
        })
        .catch((err: Error) => {
          if (!active) return
          setError(err.message)
        })
    }

    load()
    const unsubscribe = subscribeProjectsUpdated(load)

    return () => {
      active = false
      unsubscribe()
    }
  }, [])

  useEffect(() => {
    let active = true

    const loadBuilds = () => {
      fetchBuilds()
        .then((items) => {
          if (!active) return
          setBuilds(items)
        })
        .catch((err: Error) => appendLog(`Load builds failed: ${err.message}`))
    }

    loadBuilds()
    const interval = window.setInterval(loadBuilds, 5000)

    return () => {
      active = false
      window.clearInterval(interval)
    }
  }, [])

  const appendLog = (message: string) => {
    setLogs((prev) => [
      `${new Date().toLocaleTimeString()}: ${message}`,
      ...prev.slice(0, 49),
    ])
  }

  const handleCreateSample = async () => {
    try {
      setBusy(true)
      const name = `dev-${Date.now()}`
      const project = await createProject({
        name,
        minecraftVersion: '1.21.1',
        loader: 'paper',
        description: 'Generated by Dev Tools',
      })
      appendLog(`Created project ${project.name}`)
    } catch (err) {
      appendLog(`Create failed: ${(err as Error).message}`)
    } finally {
      setBusy(false)
    }
  }

  const handleImportSample = async () => {
    try {
      setBusy(true)
      const repoUrl = 'https://github.com/example/server-template'
      const project = await importProjectRepo({
        repoUrl,
        defaultBranch: 'main',
        profilePath: 'profiles/base.yml',
      })
      appendLog(`Imported repo for ${project.name}`)
    } catch (err) {
      appendLog(`Import failed: ${(err as Error).message}`)
    } finally {
      setBusy(false)
    }
  }

  const handleManifest = async (project: ProjectSummary) => {
    try {
      setBusy(true)
      const response = await triggerManifest(project.id)
      appendLog(
        `Manifest generated for ${project.name} (${response.manifest?.lastBuildId ?? 'unknown'})`,
      )
    } catch (err) {
      appendLog(`Manifest failed: ${(err as Error).message}`)
    } finally {
      setBusy(false)
    }
  }

  const handleSeedAssets = async (project: ProjectSummary) => {
    try {
      setBusy(true)
      const assets = await scanProjectAssets(project.id)
      appendLog(
        `Scanned assets for ${project.name} (${assets.plugins.length} plugins, ${assets.configs.length} configs)`,
      )
    } catch (err) {
      appendLog(`Asset scan failed: ${(err as Error).message}`)
    } finally {
      setBusy(false)
    }
  }

  return (
    <section className="panel">
      <header>
        <h2>Developer Test Tools</h2>
        <p className="muted">
          Quick helpers for exercising backend endpoints while the UI is still under construction.
        </p>
      </header>

      <div className="dev-actions">
        <button type="button" className="primary" disabled={busy} onClick={handleCreateSample}>
          Create Sample Project
        </button>
        <button type="button" className="ghost" disabled={busy} onClick={handleImportSample}>
          Import Sample Repo
        </button>
      </div>

      {error && <p className="error-text">{error}</p>}

      <div className="dev-grid">
        <div>
          <h3>Projects</h3>
          <ul className="project-list">
            {sortedProjects.map((project) => (
              <li key={project.id}>
                <div>
                  <h4>{project.name}</h4>
                  <p className="muted">
                    {project.minecraftVersion} · {project.loader.toUpperCase()}{' '}
                    {project.manifest
                      ? `· Manifest ${project.manifest.lastBuildId}`
                      : '· No manifest'}
                    {project.plugins?.length
                      ? ` · ${project.plugins.length} plugin${project.plugins.length > 1 ? 's' : ''}`
                      : ''}
                  </p>
                </div>
                <div className="dev-buttons">
                  <button
                    type="button"
                    className="ghost"
                    disabled={busy}
                    onClick={() => handleManifest(project)}
                  >
                    Generate Manifest
                  </button>
                  <button
                    type="button"
                    className="ghost"
                    disabled={busy}
                    onClick={() => handleSeedAssets(project)}
                  >
                    Scan Assets
                  </button>
                  <button
                    type="button"
                    className="ghost"
                    disabled={busy}
                    onClick={async () => {
                      try {
                        setBusy(true)
                        const build = await triggerBuild(project.id)
                        appendLog(`Queued build ${build.id} for ${project.name}`)
                        setTimeout(async () => {
                          const updated = await fetchBuild(build.id)
                          setBuilds((prev) => {
                            const copy = prev.filter((item) => item.id !== updated.id)
                            return [updated, ...copy]
                          })
                        }, 1500)
                      } catch (err) {
                        appendLog(`Build failed to queue: ${(err as Error).message}`)
                      } finally {
                        setBusy(false)
                      }
                    }}
                  >
                    Trigger Build
                  </button>
                </div>
              </li>
            ))}
          </ul>
          {sortedProjects.length === 0 && (
            <p className="empty-state">No projects yet. Use the buttons above to seed data.</p>
          )}
        </div>

        <div>
          <h3>Builds</h3>
          <div className="log-box">
            {builds.length === 0 && <p className="muted">No builds queued yet.</p>}
            {builds.length > 0 && (
              <ul>
                {builds.map((build) => (
                  <li key={build.id}>
                    <strong>{build.projectId}</strong> · {build.status.toUpperCase()} ·{' '}
                    {build.finishedAt
                      ? new Date(build.finishedAt).toLocaleTimeString()
                      : new Date(build.createdAt).toLocaleTimeString()}
                    {build.error ? ` — ${build.error}` : ''}
                  </li>
                ))}
              </ul>
            )}
          </div>
        </div>

        <div>
          <h3>Activity Log</h3>
          <div className="log-box">
            {logs.length === 0 && <p className="muted">Actions will appear here.</p>}
            {logs.length > 0 && (
              <ul>
                {logs.map((entry, index) => (
                  <li key={index}>{entry}</li>
                ))}
              </ul>
            )}
          </div>
        </div>
      </div>
    </section>
  )
}

export default TestTools

