import { useEffect, useMemo, useState } from 'react'
import {
  createProject,
  fetchProjects,
  importProjectRepo,
  triggerManifest,
  type ProjectSummary,
} from '../lib/api'
import { subscribeProjectsUpdated } from '../lib/events'

function TestTools() {
  const [projects, setProjects] = useState<ProjectSummary[]>([])
  const [busy, setBusy] = useState(false)
  const [logs, setLogs] = useState<string[]>([])
  const [error, setError] = useState<string | null>(null)

  const sortedProjects = useMemo(
    () => [...projects].sort((a, b) => (a.updatedAt < b.updatedAt ? 1 : -1)),
    [projects],
  )

  useEffect(() => {
    let active = true

    const load = () => {
      fetchProjects()
        .then((items) => {
          if (!active) return
          setProjects(items)
          setError(null)
        })
        .catch((err: Error) => {
          if (!active) return
          setError(err.message)
        })
    }

    load()
    const unsubscribe = subscribeProjectsUpdated(load)

    return () => {
      active = false
      unsubscribe()
    }
  }, [])

  const appendLog = (message: string) => {
    setLogs((prev) => [
      `${new Date().toLocaleTimeString()}: ${message}`,
      ...prev.slice(0, 49),
    ])
  }

  const handleCreateSample = async () => {
    try {
      setBusy(true)
      const name = `dev-${Date.now()}`
      const project = await createProject({
        name,
        minecraftVersion: '1.21.1',
        loader: 'paper',
        description: 'Generated by Dev Tools',
      })
      appendLog(`Created project ${project.name}`)
    } catch (err) {
      appendLog(`Create failed: ${(err as Error).message}`)
    } finally {
      setBusy(false)
    }
  }

  const handleImportSample = async () => {
    try {
      setBusy(true)
      const repoUrl = 'https://github.com/example/server-template'
      const project = await importProjectRepo({
        repoUrl,
        defaultBranch: 'main',
        profilePath: 'profiles/base.yml',
      })
      appendLog(`Imported repo for ${project.name}`)
    } catch (err) {
      appendLog(`Import failed: ${(err as Error).message}`)
    } finally {
      setBusy(false)
    }
  }

  const handleManifest = async (project: ProjectSummary) => {
    try {
      setBusy(true)
      const response = await triggerManifest(project.id)
      appendLog(
        `Manifest generated for ${project.name} (${response.manifest?.lastBuildId ?? 'unknown'})`,
      )
    } catch (err) {
      appendLog(`Manifest failed: ${(err as Error).message}`)
    } finally {
      setBusy(false)
    }
  }

  return (
    <section className="panel">
      <header>
        <h2>Developer Test Tools</h2>
        <p className="muted">
          Quick helpers for exercising backend endpoints while the UI is still under construction.
        </p>
      </header>

      <div className="dev-actions">
        <button type="button" className="primary" disabled={busy} onClick={handleCreateSample}>
          Create Sample Project
        </button>
        <button type="button" className="ghost" disabled={busy} onClick={handleImportSample}>
          Import Sample Repo
        </button>
      </div>

      {error && <p className="error-text">{error}</p>}

      <div className="dev-grid">
        <div>
          <h3>Projects</h3>
          <ul className="project-list">
            {sortedProjects.map((project) => (
              <li key={project.id}>
                <div>
                  <h4>{project.name}</h4>
                  <p className="muted">
                    {project.minecraftVersion} · {project.loader.toUpperCase()}{' '}
                    {project.manifest
                      ? `· Manifest ${project.manifest.lastBuildId}`
                      : '· No manifest'}
                  </p>
                </div>
                <div className="dev-buttons">
                  <button
                    type="button"
                    className="ghost"
                    disabled={busy}
                    onClick={() => handleManifest(project)}
                  >
                    Generate Manifest
                  </button>
                </div>
              </li>
            ))}
          </ul>
          {sortedProjects.length === 0 && (
            <p className="empty-state">No projects yet. Use the buttons above to seed data.</p>
          )}
        </div>

        <div>
          <h3>Activity Log</h3>
          <div className="log-box">
            {logs.length === 0 && <p className="muted">Actions will appear here.</p>}
            {logs.length > 0 && (
              <ul>
                {logs.map((entry, index) => (
                  <li key={index}>{entry}</li>
                ))}
              </ul>
            )}
          </div>
        </div>
      </div>
    </section>
  )
}

export default TestTools

