import { useEffect, useMemo, useState } from 'react'
import {
  createProject,
  fetchProjects,
  importProjectRepo,
  triggerManifest,
  triggerBuild,
  fetchBuilds,
  fetchBuild,
  scanProjectAssets,
  fetchGitHubRepos,
  createGitHubRepo,
  type ProjectSummary,
  type BuildJob,
  type GitHubRepo,
} from '../lib/api'
import { subscribeProjectsUpdated } from '../lib/events'
import { Alert, Anchor, Checkbox, Code, Group, NativeSelect, ScrollArea, SimpleGrid, Stack, Text, TextInput, Title } from '@mantine/core'
import { Button, Card, CardContent } from '../components/ui'

function TestTools() {
  const [projects, setProjects] = useState<ProjectSummary[]>([])
  const [busy, setBusy] = useState(false)
  const [logs, setLogs] = useState<string[]>([])
  const [error, setError] = useState<string | null>(null)
  const [builds, setBuilds] = useState<BuildJob[]>([])
  const [repos, setRepos] = useState<GitHubRepo[]>([])
  const [owners, setOwners] = useState<Array<{ login: string; avatarUrl: string; htmlUrl: string }>>([])
  const [selectedOrg, setSelectedOrg] = useState<string>('')
  const [newRepoName, setNewRepoName] = useState('')
  const [newRepoPrivate, setNewRepoPrivate] = useState(true)

  const sortedProjects = useMemo(
    () => [...projects].sort((a, b) => (a.updatedAt < b.updatedAt ? 1 : -1)),
    [projects],
  )

  useEffect(() => {
    let active = true

    const load = () => {
      fetchProjects()
        .then((items) => {
          if (!active) return
          setProjects(items)
          setError(null)
        })
        .catch((err: Error) => {
          if (!active) return
          setError(err.message)
        })
    }

    load()
    const unsubscribe = subscribeProjectsUpdated(load)

    return () => {
      active = false
      unsubscribe()
    }
  }, [])

  useEffect(() => {
    let active = true

    const loadBuilds = () => {
      fetchBuilds()
        .then((items) => {
          if (!active) return
          setBuilds(items)
        })
        .catch((err: Error) => appendLog(`Load builds failed: ${err.message}`))
    }

    loadBuilds()
    const interval = window.setInterval(loadBuilds, 5000)

    return () => {
      active = false
      window.clearInterval(interval)
    }
  }, [])

  useEffect(() => {
    fetchGitHubRepos()
      .then((data) => {
        setRepos(data.repos)
        const uniqueOwners = [
          { login: 'self', avatarUrl: data.owner.avatarUrl, htmlUrl: data.owner.htmlUrl },
          ...data.orgs,
        ]
        setOwners(uniqueOwners)
        setSelectedOrg((prev) => {
          if (prev && uniqueOwners.some((org) => org.login === prev)) {
            return prev
          }
          return uniqueOwners[0]?.login ?? ''
        })
      })
      .catch((err: Error) => appendLog(`Load GitHub repos failed: ${err.message}`))
  }, [])

  const appendLog = (message: string) => {
    setLogs((prev) => [
      `${new Date().toLocaleTimeString()}: ${message}`,
      ...prev.slice(0, 49),
    ])
  }

  const handleCreateSample = async () => {
    try {
      setBusy(true)
      const name = `dev-${Date.now()}`
      const project = await createProject({
        name,
        minecraftVersion: '1.21.1',
        loader: 'paper',
        description: 'Generated by Dev Tools',
      })
      appendLog(`Created project ${project.name}`)
    } catch (err) {
      appendLog(`Create failed: ${(err as Error).message}`)
    } finally {
      setBusy(false)
    }
  }

  const handleImportSample = async () => {
    try {
      setBusy(true)
      const repoUrl = 'https://github.com/example/server-template'
      const project = await importProjectRepo({
        repoUrl,
        defaultBranch: 'main',
        profilePath: 'profiles/base.yml',
      })
      appendLog(`Imported repo for ${project.name}`)
    } catch (err) {
      appendLog(`Import failed: ${(err as Error).message}`)
    } finally {
      setBusy(false)
    }
  }

  const handleManifest = async (project: ProjectSummary) => {
    try {
      setBusy(true)
      const response = await triggerManifest(project.id)
      appendLog(
        `Manifest generated for ${project.name} (${response.manifest?.lastBuildId ?? 'unknown'})`,
      )
    } catch (err) {
      appendLog(`Manifest failed: ${(err as Error).message}`)
    } finally {
      setBusy(false)
    }
  }

  const handleSeedAssets = async (project: ProjectSummary) => {
    try {
      setBusy(true)
      const assets = await scanProjectAssets(project.id)
      appendLog(
        `Scanned assets for ${project.name} (${assets.plugins.length} plugins, ${assets.configs.length} configs)`,
      )
    } catch (err) {
      appendLog(`Asset scan failed: ${(err as Error).message}`)
    } finally {
      setBusy(false)
    }
  }

  return (
    <Stack gap="lg" p="lg">
      <Card>
        <CardContent>
          <Stack gap="md">
            <Stack gap={4}>
              <Title order={2}>Developer Test Tools</Title>
              <Text size="sm" c="dimmed">
                Quick helpers for exercising backend endpoints while the UI is still under construction.
              </Text>
            </Stack>

            <Group>
              <Button type="button" variant="primary" disabled={busy} onClick={handleCreateSample}>
                Create Sample Project
              </Button>
              <Button type="button" variant="ghost" disabled={busy} onClick={handleImportSample}>
                Import Sample Repo
              </Button>
            </Group>

            {error && (
              <Alert color="red" title="Error">
                {error}
              </Alert>
            )}
          </Stack>
        </CardContent>
      </Card>

      <SimpleGrid cols={{ base: 1, md: 2 }} spacing="lg">
        <Card>
          <CardContent>
            <Stack gap="md">
              <Title order={3}>GitHub Repositories</Title>
              <form
                onSubmit={async (event) => {
                  event.preventDefault()
                  if (!selectedOrg || !newRepoName.trim()) {
                    appendLog('Org and repo name are required')
                    return
                  }
                  try {
                    setBusy(true)
                    const repo = await createGitHubRepo(selectedOrg, {
                      name: newRepoName.trim(),
                      private: newRepoPrivate,
                    })
                    appendLog(`Created repo ${repo.fullName}`)
                    setRepos((prev) => [repo, ...prev])
                    setNewRepoName('')
                  } catch (err) {
                    appendLog(`Repo creation failed: ${(err as Error).message}`)
                  } finally {
                    setBusy(false)
                  }
                }}
              >
                <Stack gap="md">
                  <NativeSelect
                    label="Organization / Owner"
                    id="org-select"
                    value={selectedOrg}
                    onChange={(event) => setSelectedOrg(event.target.value)}
                    data={owners.map((owner) => ({
                      value: owner.login,
                      label: owner.login,
                    }))}
                  />

                  <TextInput
                    label="Repository name"
                    id="repo-name"
                    value={newRepoName}
                    onChange={(event) => setNewRepoName(event.target.value)}
                    placeholder="my-server-manager"
                  />

                  <Checkbox
                    label="Private repository"
                    checked={newRepoPrivate}
                    onChange={(event) => setNewRepoPrivate(event.target.checked)}
                  />

                  <Button type="submit" variant="primary" disabled={busy}>
                    Create Repo
                  </Button>
                </Stack>
              </form>

              <Stack gap="sm">
                {repos.length === 0 ? (
                  <Text size="sm" c="dimmed">No repositories found.</Text>
                ) : (
                  <Stack gap="xs">
                    {repos.map((repo) => (
                      <Card key={repo.id}>
                        <CardContent>
                          <Group justify="space-between" align="center">
                            <Group gap="xs">
                              <Text fw={600}>{repo.fullName}</Text>
                              <Text>{repo.private ? '🔒' : '🌐'}</Text>
                            </Group>
                            <Anchor href={repo.htmlUrl} target="_blank" rel="noreferrer" size="sm">
                              View
                            </Anchor>
                          </Group>
                        </CardContent>
                      </Card>
                    ))}
                  </Stack>
                )}
              </Stack>
            </Stack>
          </CardContent>
        </Card>

        <Card>
          <CardContent>
            <Stack gap="md">
              <Title order={3}>Projects</Title>
              {sortedProjects.length === 0 ? (
                <Text size="sm" c="dimmed">No projects yet. Use the buttons above to seed data.</Text>
              ) : (
                <Stack gap="md">
                  {sortedProjects.map((project) => (
                    <Card key={project.id}>
                      <CardContent>
                        <Stack gap="sm">
                          <Group justify="space-between" align="flex-start">
                            <Stack gap={4}>
                              <Title order={4}>{project.name}</Title>
                              <Text size="sm" c="dimmed">
                                {[
                                  project.minecraftVersion,
                                  project.loader.toUpperCase(),
                                  project.repo?.fullName ?? null,
                                  project.manifest
                                    ? `Manifest ${project.manifest.lastBuildId}`
                                    : 'No manifest',
                                  project.plugins?.length
                                    ? `${project.plugins.length} plugin${project.plugins.length > 1 ? 's' : ''}`
                                    : null,
                                ]
                                  .filter(Boolean)
                                  .join(' · ')}
                              </Text>
                            </Stack>
                            <Group gap="xs" wrap="wrap">
                              <Button
                                type="button"
                                variant="ghost"
                                disabled={busy}
                                onClick={() => handleManifest(project)}
                              >
                                Generate Manifest
                              </Button>
                              <Button
                                type="button"
                                variant="ghost"
                                disabled={busy}
                                onClick={() => handleSeedAssets(project)}
                              >
                                Scan Assets
                              </Button>
                              <Button
                                type="button"
                                variant="ghost"
                                disabled={busy}
                                onClick={async () => {
                                  try {
                                    setBusy(true)
                                    const build = await triggerBuild(project.id)
                                    appendLog(`Queued build ${build.id} for ${project.name}`)
                                    setTimeout(async () => {
                                      const updated = await fetchBuild(build.id)
                                      setBuilds((prev) => {
                                        const copy = prev.filter((item) => item.id !== updated.id)
                                        return [updated, ...copy]
                                      })
                                    }, 1500)
                                  } catch (err) {
                                    appendLog(`Build failed to queue: ${(err as Error).message}`)
                                  } finally {
                                    setBusy(false)
                                  }
                                }}
                              >
                                Trigger Build
                              </Button>
                            </Group>
                          </Group>
                        </Stack>
                      </CardContent>
                    </Card>
                  ))}
                </Stack>
              )}
            </Stack>
          </CardContent>
        </Card>

        <Card>
          <CardContent>
            <Stack gap="md">
              <Title order={3}>Builds</Title>
              {builds.length === 0 ? (
                <Text size="sm" c="dimmed">No builds queued yet.</Text>
              ) : (
                <ScrollArea>
                  <Stack gap="xs">
                    {builds.map((build) => (
                      <Card key={build.id}>
                        <CardContent>
                          <Text size="sm">
                            <Text component="span" fw={600}>{build.projectId}</Text>
                            {' · '}
                            {build.status.toUpperCase()}
                            {' · '}
                            {build.finishedAt
                              ? new Date(build.finishedAt).toLocaleTimeString()
                              : new Date(build.createdAt).toLocaleTimeString()}
                            {build.error && (
                              <>
                                {' — '}
                                <Text component="span" c="red">{build.error}</Text>
                              </>
                            )}
                          </Text>
                        </CardContent>
                      </Card>
                    ))}
                  </Stack>
                </ScrollArea>
              )}
            </Stack>
          </CardContent>
        </Card>

        <Card>
          <CardContent>
            <Stack gap="md">
              <Title order={3}>Activity Log</Title>
              {logs.length === 0 ? (
                <Text size="sm" c="dimmed">Actions will appear here.</Text>
              ) : (
                <ScrollArea>
                  <Code block style={{ whiteSpace: 'pre-wrap', wordBreak: 'break-all' }}>
                    {logs.join('\n')}
                  </Code>
                </ScrollArea>
              )}
            </Stack>
          </CardContent>
        </Card>
      </SimpleGrid>
    </Stack>
  )
}

export default TestTools

